branch-defaults:
  master:
    environment: expressapp-dev
    group_suffix: null
global:
  application_name: expressapp
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: null
  sc: git
